# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fal_application_2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.0'
pod 'Kingfisher'
  # Pods for fal_application_2

end
